---
# tasks file for ansible-role-nis

- name: template in yp.conf on non-servers
  template:
    src: yp.conf.j2
    dest: /etc/yp.conf
  when: not nis_server|bool
  notify:
    - restart rpcbind
    - restart ypbind

- name: install nis server packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nis_server_packages_ubuntu }}"
  when: nis_server|bool
  notify:
    - restart rpcbind
    - restart ypbind
    - restart ypserv

- name: install nis common packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nis_packages_ubuntu }}"
  notify:
    - restart ypbind
    - restart ypserv

- name : template in nsswitch - conditionals inside template
  template:
    src: nsswitch.conf.j2
    dest: /etc/nsswitch.conf
  when: not nis_server|bool and nis_manage_nsswitch|bool
  notify:
    - restart rpcbind
    - restart ypbind

- name : template in /var/yp/securenets
  template:
    src: securenets.j2
    dest: /var/yp/securenets
  when: nis_server|bool
  notify:
    - restart rpcbind
    - restart ypserv

- name : template in yp Make cronjob
  template:
    src: yp.cron.j2
    dest: /etc/cron.hourly/yp.cron
    mode: 0755
    owner: root
    group: root
    backup: no
  when: nis_server|bool

- name: enable and start yp server daemons
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  when: nis_server|bool
  with_items: "{{ nis_server_daemons }}"
  notify:
    - restart ypserv

- name: enable and start nscd
  service:
    name: nscd
    enabled: "{{ nis_nscd_enabled }}"
    state: "{{ nis_nscd_state }}"
  when: nis_manage_nscd|bool

